version: "3.10"

services:
  database:
    image: "postgres"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Bangkok
      - PGTZ=Asia/Bangkok
    command: >
        -c work_mem=512MB
        -c maintenance_work_mem=512MB
        -c max_wal_size=5GB
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - database
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.server
    command: npm start
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - database
