FROM postgres:latest

ENV POSTGRES_HOST_AUTH_METHOD=trust
ENV TZ=Asia/Bangkok
ENV PGTZ=Asia/Bangkok

COPY database-data /

COPY docker-script/database-intializer.sh /docker-entrypoint-initdb.d/init-user-db.sh
